services:
  card-battler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./server/src:/app/src
    restart: unless-stopped